env: "local"
grpc:
  port: 4041
  timeout: 4s
storage:
  connection_string: "host=localhost port=5001 user=postgres password=admin dbname=golang_posts sslmode=disable"
  migration_path: "./migrations"
